name: Deploy backend to Lightsail

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Testar conexão SSH com Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            uname -a
            whoami
          timeout: 60s
          command_timeout: 30m
          disable_strict_host_key_checking: true

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build backend
        working-directory: backend/sisacao-backend
        run: ./mvnw clean package -DskipTests

      - name: Upload artifact to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          source: backend/sisacao-backend/target/sisacao-backend-0.0.1-SNAPSHOT.jar
          target: /home/deploy/sisacao/app/
          overwrite: true
          strip_components: 3
          timeout: 120s
          disable_strict_host_key_checking: true

      - name: Restart service remotely
        # Consulte docs/lightsail-deploy.md para saber quando configurar o segredo
        # LIGHTSAIL_SUDO_PASSWORD ou como habilitar sudo sem senha.
        uses: appleboy/ssh-action@v1.0.3
        env:
          LIGHTSAIL_SUDO_PASSWORD: ${{ secrets.LIGHTSAIL_SUDO_PASSWORD }}
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          envs: LIGHTSAIL_SUDO_PASSWORD
          script: |
            set -euo pipefail

            run_sudo() {
              if [ -n "${LIGHTSAIL_SUDO_PASSWORD:-}" ]; then
                echo "$LIGHTSAIL_SUDO_PASSWORD" | sudo -S -p '' "$@"
                return
              fi

              if sudo -n "$@"; then
                return
              fi

              status=$?
              if sudo -n true >/dev/null 2>&1; then
                echo "sudo command failed with status ${status}: $*" >&2
                return ${status}
              fi

              echo "sudo password required: configure passwordless sudo for deploy or set LIGHTSAIL_SUDO_PASSWORD secret" >&2
              return 1
            }

            run_sudo install -d /opt/sisacao/app/
            run_sudo mv /home/deploy/sisacao/app/sisacao-backend-0.0.1-SNAPSHOT.jar /opt/sisacao/app/sisacao-backend.jar
            run_sudo systemctl daemon-reload
            run_sudo systemctl restart sisacao-backend.service
            run_sudo systemctl status sisacao-backend.service --no-pager
          timeout: 60s
          command_timeout: 30m
          disable_strict_host_key_checking: true
