name: Deploy backend to Lightsail

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Testar conexão SSH com Lightsail
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            uname -a
            whoami
          timeout: 60s
          command_timeout: 30m
          disable_strict_host_key_checking: true

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build backend
        working-directory: backend/sisacao-backend
        run: ./mvnw clean package -DskipTests

      - name: Upload artifact to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          source: backend/sisacao-backend/target/sisacao-backend-0.0.1-SNAPSHOT.jar
          target: /opt/sisacao/app/
          overwrite: true
          strip_components: 3
          timeout: 120s
          disable_strict_host_key_checking: true

      - name: Restart service remotely
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.194.252.70
          username: deploy
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo mv /opt/sisacao/app/sisacao-backend-0.0.1-SNAPSHOT.jar /opt/sisacao/app/sisacao-backend.jar
            sudo systemctl daemon-reload
            sudo systemctl restart sisacao-backend.service
            sudo systemctl status sisacao-backend.service --no-pager
          timeout: 60s
          command_timeout: 30m
          disable_strict_host_key_checking: true
